/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.primeidea.camhunter.gui;

import com.primeidea.camhunter.core.InsertFileDataToJTable;
import com.primeidea.camhunter.core.Page;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author pro
 */
public class MainPanel extends javax.swing.JPanel {

    private static final String[] HEADERS = {
        "Addres",
        "TypeCam",
        "Log",
        "Pass",
        "Free",
        "Rec",
        "Private"
    };
    DefaultTableModel model;
    String[] columnNames = {"First Name", "Last Name", "", ""};
    Object[][] data = {
        {"Homer", "Simpson", ">", "X"},
        {"Madge", "Simpson", ">", "X"},
        {"Bart", "Simpson", ">", "X"},
        {"Lisa", "Simpson", ">", "X"},};
    //DefaultTableModel model = new DefaultTableModel(data, columnNames);

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        model = (DefaultTableModel) tblCurrentJob.getModel();
        model.setColumnIdentifiers(HEADERS);
//        for USE, if table was container to jobs
//        tblAllJob.setModel(model);
//        Action delete = new AbstractAction() {
//            public void actionPerformed(ActionEvent e) {
//                JTable table = (JTable) e.getSource();
//                int modelRow = Integer.valueOf(e.getActionCommand());
//                ((DefaultTableModel) table.getModel()).removeRow(modelRow);
//            }
//        };
//        Action startStop = new AbstractAction() {
//            public void actionPerformed(ActionEvent e) {
//                JTable table = (JTable) e.getSource();
//                int modelRow = Integer.valueOf(e.getActionCommand());
//                //((DefaultTableModel) table.getModel()).setValueAt(table, modelRow, 3);
//            }
//        };
//        ButtonColumn buttonColumn = new ButtonColumn(tblAllJob, startStop, 2, delete, 3);
//        buttonColumn.setMnemonic(KeyEvent.VK_D);
//
    }

    public void setjPanel3(JPanel pnl) {
        pnl.setVisible(true);
        this.jPanel3.add(pnl);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPM = new javax.swing.JPopupMenu();
        jLoad = new javax.swing.JMenuItem();
        jSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jClearTbl = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnControlAllJob = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAllJob = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurrentJob = new javax.swing.JTable();

        jLoad.setText("Загрузить");
        jLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoadActionPerformed(evt);
            }
        });
        jPM.add(jLoad);

        jSave.setText("Сохранить");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });
        jPM.add(jSave);
        jPM.add(jSeparator1);

        jClearTbl.setText("Очистить");
        jPM.add(jClearTbl);

        jPanel2.setBorder(null);
        jPanel2.setPreferredSize(new java.awt.Dimension(180, 83));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setAutoscrolls(true);
        jPanel3.setMaximumSize(new java.awt.Dimension(180, 20));
        jPanel3.setPreferredSize(new java.awt.Dimension(180, 20));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setMinimumSize(new java.awt.Dimension(180, 45));
        jPanel4.setPreferredSize(new java.awt.Dimension(180, 45));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Очистить");
        jButton2.setAlignmentY(0.0F);
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 40));

        btnControlAllJob.setText("Старт");
        btnControlAllJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlAllJobActionPerformed(evt);
            }
        });
        jPanel4.add(btnControlAllJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        tblAllJob.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblAllJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblAllJob);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblCurrentJob.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblCurrentJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tblCurrentJob.setComponentPopupMenu(jPM);
        jScrollPane1.setViewportView(tblCurrentJob);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Сканнер", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoadActionPerformed
        Preferences prefs = Preferences.userRoot().node(this.getClass().getName());
        String LAST_USED_FOLDER = "c:\\";
        JFileChooser chooser = new JFileChooser(prefs.get(LAST_USED_FOLDER, new File(".").getAbsolutePath()));
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            //                BufferedReader br = new BufferedReader(new FileReader(chooser.getSelectedFile().toString()));
//                Object[] tableLines = br.lines().toArray();
//                for (int i = 0; i < tableLines.length; i++) {
//                    String line = tableLines[i].toString().trim();
//                    String[] dataRow = line.split("");
//                    model.addRow(dataRow);
//                }
//            List<String> lines = null;
            List<String> lines = null;
            try {
                lines = Files.readAllLines(Paths.get(chooser.getSelectedFile().toString()), StandardCharsets.UTF_8);
            } catch (IOException ex) {

            }
//            for (int i = 0; i < lines.size(); i++) {
//                findCamNoPass.addElement(lines.get(i));
//            }
            InsertFileDataToJTable model = new InsertFileDataToJTable(chooser.getSelectedFile().toString());
            tblCurrentJob.setModel(model);
//prefs.put(LAST_USED_FOLDER, "Ок");
        }
    }//GEN-LAST:event_jLoadActionPerformed
    private String getCurrentTime() {
        Date curDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy' 'kk.mm.ss.S");
        String currentDate = dateFormat.format(curDate);
        return currentDate;
    }
    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // Выгрузить список камер в файл
        List<String> result = new ArrayList<>();
        result.clear();
        for (int i = 0; i < tblCurrentJob.getModel().getRowCount() - 1; i++) {
            result.add((String) tblCurrentJob.getModel().getValueAt(i, 1));
        }
        String fileName = "";
        String ip1st = (String) tblCurrentJob.getModel().getValueAt(0, 1);
        int pos1st = ip1st.indexOf(":");
        String start1st = ip1st.substring(0, pos1st);

        String ip2nd = (String) tblCurrentJob.getModel().getValueAt(tblCurrentJob.getModel().getRowCount() - 2, 1);
        int pos2nd = ip2nd.indexOf(":");
        String start2nd = ip2nd.substring(0, pos2nd);
        fileName = start1st + "_" + start2nd + " Defeway_" + getCurrentTime() + ".html";

        Page html = new Page(fileName, result);
        html.setHeight("200");
        html.setWidth("250");
        html.createPage();
    }//GEN-LAST:event_jSaveActionPerformed

    private void btnControlAllJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlAllJobActionPerformed
        if (btnControlAllJob.isSelected()) {
            btnControlAllJob.setText("Стоп");
        }
        else {
            btnControlAllJob.setText("Старт");   
        }
    }//GEN-LAST:event_btnControlAllJobActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnControlAllJob;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem jClearTbl;
    private javax.swing.JMenuItem jLoad;
    private javax.swing.JPopupMenu jPM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenuItem jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblAllJob;
    private javax.swing.JTable tblCurrentJob;
    // End of variables declaration//GEN-END:variables
}
